services:
  file-service:
    build:
      context: .
      dockerfile: file-service/Dockerfile
    ports:
      - "8081:8080"
    environment:
      HEALTH_PORT: "8080"
      MTLS_PORT: "8443"
      DEBUG: ${DEBUG:-false}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME:?}
      AWS_PROFILE: ${AWS_PROFILE:?}
      AWS_REGION: ${AWS_REGION:?}
      TLS_CERT_FILE: /certs/file-service.pem
      TLS_KEY_FILE: /certs/file-service-key.pem
      TLS_CA_CERT_FILE: /certs/ca.pem
    volumes:
      # reuse credentials from local env
      - ~/.aws:/home/appuser/.aws:ro
      - ./certs:/certs:ro

  api-service:
    build:
      context: .
      dockerfile: api-service/Dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      DEBUG: ${DEBUG:-false}
      FILE_SERVICE_URL: https://file-service:8443
      TLS_CERT_FILE: /certs/api-service.pem
      TLS_KEY_FILE: /certs/api-service-key.pem
      TLS_CA_CERT_FILE: /certs/ca.pem
    volumes:
      - ./certs:/certs:ro
    depends_on:
      file-service:
        condition: service_healthy
